const fs = require("node:fs");
const path = require("node:path");

const { withAppBuildGradle } = require("expo/config-plugins");

/**
 * Signs locally built release APKs with the same keystore EAS uses.
 *
 * Why this exists: the Google Maps Android key is restricted to this package name plus
 * the SHA-1 of the EAS release certificate. Expo's generated build.gradle signs release
 * builds with the throwaway debug keystore, so a locally built APK presents a different
 * certificate, Google refuses to issue a map token, and the MapView renders as a black
 * rectangle with only the Google watermark drawn on top. Nothing in the app code is
 * wrong, so the fix belongs in the build, not the screen.
 *
 * Signing with the real keystore also means a local build installs straight over an EAS
 * build instead of failing with a signature mismatch.
 *
 * The android directory is gitignored and regenerated by `expo prebuild`, which wipes any
 * edit made to build.gradle by hand. A config plugin runs as part of prebuild, so the
 * change is reapplied every time.
 *
 * Presence of the credentials decides whether this does anything. On EAS the files are
 * absent, because they are gitignored, so the plugin is a no-op and EAS keeps injecting
 * its own credentials exactly as before. Run scripts/pull-release-keystore.mjs to create
 * them on a development machine.
 */
const CREDENTIALS_DIR = path.join(__dirname, "..", "credentials");
const PROPERTIES_PATH = path.join(
  CREDENTIALS_DIR,
  "release-signing.properties",
);

/** Gradle is happier with forward slashes on Windows, in Groovy string literals. */
function toGradlePath(value) {
  return value.replace(/\\/g, "/");
}

function injectReleaseSigningConfig(contents, propertiesPath) {
  const anchor = "signingConfigs {";
  const at = contents.indexOf(anchor);

  if (at === -1) {
    throw new Error(
      "withLocalReleaseSigning: no signingConfigs block found in app/build.gradle.",
    );
  }

  // Read at Gradle evaluation time rather than baking the passwords into build.gradle,
  // so the generated file holds a path and nothing secret.
  const block = `
        release {
            def spinnerSigningFile = file('${toGradlePath(propertiesPath)}')
            def spinnerSigning = new Properties()
            spinnerSigningFile.withInputStream { spinnerSigning.load(it) }
            storeFile file(spinnerSigning['storeFile'])
            storePassword spinnerSigning['storePassword']
            keyAlias spinnerSigning['keyAlias']
            keyPassword spinnerSigning['keyPassword']
        }`;

  return (
    contents.slice(0, at + anchor.length) +
    block +
    contents.slice(at + anchor.length)
  );
}

function pointReleaseBuildTypeAtIt(contents) {
  // Anchored through buildTypes and into the release block so the debug build type,
  // which legitimately uses signingConfigs.debug and appears first, is left alone.
  const pattern =
    /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/;

  if (!pattern.test(contents)) {
    throw new Error(
      "withLocalReleaseSigning: the release build type does not use signingConfigs.debug, " +
        "so the template has changed and this plugin needs revisiting.",
    );
  }

  return contents.replace(pattern, "$1signingConfig signingConfigs.release");
}

module.exports = function withLocalReleaseSigning(config) {
  if (!fs.existsSync(PROPERTIES_PATH)) return config;

  return withAppBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== "groovy") {
      throw new Error(
        "withLocalReleaseSigning: expected a Groovy build.gradle.",
      );
    }

    let contents = gradleConfig.modResults.contents;

    // Idempotent: prebuild can run more than once against the same file.
    if (!contents.includes("spinnerSigningFile")) {
      contents = injectReleaseSigningConfig(contents, PROPERTIES_PATH);
      contents = pointReleaseBuildTypeAtIt(contents);
    }

    gradleConfig.modResults.contents = contents;
    return gradleConfig;
  });
};
