// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Spinner.Api.Database;

#nullable disable

namespace Spinner.Api.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710000100_Phase2CustomerBookingFlow")]
    partial class Phase2CustomerBookingFlow
    {
    }
}
