// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spinner.Api.Database;

#nullable disable

namespace Spinner.Api.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709161904_Phase1BusinessSettingsAndServices")]
    partial class Phase1BusinessSettingsAndServices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spinner.Api.Domain.Business.BusinessSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCashOnDeliveryEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailBookingConfirmedEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailCompletedEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailReceiptEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQrCodeOnlinePaymentEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmsBookingConfirmedEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmsBookingReceivedEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmsCompletedEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmsPickedUpEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmsReadyForDeliveryEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OperatingHours")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PickupTimeWindows")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BusinessSettings", (string)null);
                });

            modelBuilder.Entity("Spinner.Api.Domain.Services.LaundryService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DeliveryFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("SupportsPickupAndDelivery")
                        .HasColumnType("boolean");

                    b.Property<string>("UnitLabel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LaundryServices", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
